fix: missing instrumentation classes during configuration
When auto-instrumention classes are declared but cannot be loaded, the registry will report an error to logger
and then proceed with the installation.

Before:

```
Could not install OpenTelemetry::Instrumentation::Faraday because it was not found

OpenTelemetry error: unexpected configuration error due to undefined method `name' for nil:NilClass - OpenTelemetry::SDK::ConfigurationError
```

After:
```
Could not install OpenTelemetry::Instrumentation::Faraday because it was not found
```