fix: handle missing job metadata
When jobs are enqueued before opentelemetry is enabled, they don't have `metadata` added to the serialized form.
If the worker already has opentelemetry enabled, it assumes `metadata` is present and attempts to deserialize it, causing a crash:

```
ActiveJob::DeserializationError:
Error while trying to deserialize arguments: undefined method `map' for nil:NilClass
.../activejob-6.0.4.1/lib/active_job/arguments.rb:42:in `deserialize'
.../activejob-6.0.4.1/lib/active_job/core.rb:170:in `deserialize_arguments'
.../opentelemetry-instrumentation-active_job-0.1.5/lib/opentelemetry/instrumentation/active_job/patches/base.rb:30:in `deserialize'
.../activejob-6.0.4.1/lib/active_job/core.rb:52:in `deserialize'
.../activejob-6.0.4.1/lib/active_job/execution.rb:24:in `block in execute'
.../activesupport-6.0.4.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
.../activejob-6.0.4.1/lib/active_job/railtie.rb:43:in `block (4 levels) in <class:Railtie>'
.../activesupport-6.0.4.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
.../activesupport-6.0.4.1/lib/active_support/reloader.rb:72:in `block in wrap'
.../activesupport-6.0.4.1/lib/active_support/execution_wrapper.rb:88:in `wrap'
.../activesupport-6.0.4.1/lib/active_support/reloader.rb:71:in `wrap'
.../activejob-6.0.4.1/lib/active_job/railtie.rb:42:in `block (3 levels) in <class:Railtie>'
.../activesupport-6.0.4.1/lib/active_support/callbacks.rb:121:in `instance_exec'
.../activesupport-6.0.4.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
.../activesupport-6.0.4.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
.../activejob-6.0.4.1/lib/active_job/execution.rb:23:in `execute'
```

This happened to us due to some misconfiguration, where opentelemetry was enabled on the workers but disabled on the web servers.
But this might also happen during a rolling restart if new workers with opentelemetry enabled come up before new web servers.