fix(active_job): Fix deserialization of jobs that are missing metadata
During a rolling deployment, we may get jobs from applications that do
not have OpenTelemetry instrumentation. In such cases, jobs failed to
deserialize with the following error:
```
Minitest::UnexpectedError: ActiveJob::DeserializationError: Error while trying to deserialize arguments: undefined method `map' for nil:NilClass
    ~/.gem/ruby/2.7.5/gems/activejob-7.0.2.3/lib/active_job/arguments.rb:42:in `deserialize'
    ~/.gem/ruby/2.7.5/gems/activejob-7.0.2.3/lib/active_job/core.rb:190:in `deserialize_arguments'
    ~/opensource/opentelemetry-ruby/instrumentation/active_job/lib/opentelemetry/instrumentation/active_job/patches/base.rb:30:in `deserialize'
    ~/opensource/opentelemetry-ruby/instrumentation/active_job/test/instrumentation/active_job/patches/base_test.rb:40:in `block (3 levels) in <top (required)>'
```

This commit fixes this issue.